# This is a basic workflow to help you get started with Actions

name: CI-Test

on:
 push:
   branches:
   - "*"
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ci-kubesphere-0

    steps:
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: |
          sudo apt update
          sudo apt install git wget make -y
          sudo wget https://go.dev/dl/go1.21.4.linux-amd64.tar.gz 
          sudo rm -rf /usr/local/go && sudo tar -C /usr/local -xzf go1.21.4.linux-amd64.tar.gz
          export PATH=$PATH:/usr/local/go/bin
          git clone https://github.com/kubesphere/kubekey.git --depth=1
          cd kubekey 
          make kk
