# This is a basic workflow to help you get started with Actions

name: CI-Test

on:
 push:
   branches:
   - "*"
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ci-kubesphere-0

    steps:
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: |
          git clone https://github.com/kubesphere/kubekey.git --depth=1
          cd kubekey 
          make kk
