# This is a basic workflow to help you get started with Actions

name: CI

on:
  schedule:
    # This is a UTC time
    - cron: "0 16 * * *"

  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: master

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: |
          git config --global user.email kubesphere@kubesphere.io
          git config --global user.name kubesphere
          git remote set-url origin https://${{ secrets.GITHUB_TOKEN }}@github.com/CloudNativeTools/kk-pkg-upgrade
          git remote add kubesphere https://github.com/kubesphere/kubesphere.git
          git fetch kubesphere  
          #git checkout -b ks-master kubesphere/master
          #git checkout master
          git rebase kubesphere/master
          #git rebase ks-master
          rm -rf .github
          git add .
          git commit -m "remove kubesphere actions"
          git push origin master:master --force


