name: patch release
on:
  issues:
    types: [opened, reopened]

jobs:
  patch-release:
    runs-on: ubuntu-latest
    steps:
    - run: |       
        echo "${{ github.event.issue.body }}"  > issue.txt

        cat issue.txt
