name: patch release
on:
  issues:
    types: [opened, reopened]

jobs:
  patch-release:
    runs-on: ubuntu-latest
    steps:
    - run: |       
        # echo "${{ github.event.issue.body }}" 
        name=$(echo "${{ github.event.issue.body }}" | grep -oP '(?<=### 组件名称\n\n).+')
        version=$(echo "${{ github.event.issue.body }}" | grep -oP '(?<=### 版本号\n\n).+')

        echo $name
        echo $version
